# @name login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "jojo@academia.com",
    "password": "password123"
}

###

GET http://localhost:3000/professor/686e9593f7793df5b73c8cbb/availability
Authorization: Bearer {{login.response.body.token}}
